# Generated by Django 5.1.4 on 2024-12-23 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], max_length=50, verbose_name='Genre')),
                ('date_sortie', models.DateField(verbose_name='Date de Sortie')),
                ('casting', models.TextField(help_text='Liste des acteurs principaux séparés par des virgules.')),
                ('duree', models.PositiveIntegerField(help_text='Durée du film en minutes.')),
                ('affiche', models.ImageField(upload_to='films_affiches/')),
                ('note_moyenne', models.FloatField(default=0.0)),
            ],
        ),
    ]
