# Generated by Django 5.1.4 on 2024-12-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='note_moyenne',
        ),
    ]
