# Generated by Django 5.1.4 on 2024-12-23 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('theater', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='critique',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.film'),
        ),
        migrations.AddField(
            model_name='critique',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='critique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.critique'),
        ),
        migrations.AlterUniqueTogether(
            name='critique',
            unique_together={('film', 'utilisateur')},
        ),
    ]
